version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/ArmaBotCs" # Checks the entire repository
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/ArmaBotCs" # Checks the entire repository
    schedule:
      interval: "weekly"
