name: Build and Deploy to Kubernetes

on:
  push:
    branches: [ main ]
    
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gemberkoekje/armabotcs

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version from csproj
      id: get_version
      run: |
        VERSION=$(grep -oPm1 "(?<=<InformationalVersion>)[^<]+" ArmaBotCs/ArmaBotCs/ArmaBotCs.csproj)
        if [ -z "$VERSION" ]; then
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" ArmaBotCs/ArmaBotCs/ArmaBotCs.csproj)
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Show version in summary
      run: |
        echo "::notice title=Build Version::${{ steps.get_version.outputs.version }}-${{ github.run_number }}"

    - name: Add version to job summary
      run: |
        echo "## Build Version" >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.get_version.outputs.version }}-${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./ArmaBotCs
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.version }}-${{ github.run_number }}
